#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libodfgen
Version  : 0.1.7
Release  : 3
URL      : https://dev-www.libreoffice.org/src/libodfgen-0.1.7.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libodfgen-0.1.7.tar.xz
Summary  : Library to generate ODF documents from librevenge's api calls
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: libodfgen-lib = %{version}-%{release}
Requires: libodfgen-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)

%description
DESCRIPTION:
libodfgen is a library for generating documents in (surprise!) Open
Document Format (ODF). It provides generator implementations for all
document interfaces supported by librevenge:
* text documents
* vector drawings
* presentations
* spreadsheets
As these APIs are used by multiple libraries, libodfgen can be used to
generate ODF from many sources.

%package dev
Summary: dev components for the libodfgen package.
Group: Development
Requires: libodfgen-lib = %{version}-%{release}
Provides: libodfgen-devel = %{version}-%{release}

%description dev
dev components for the libodfgen package.


%package doc
Summary: doc components for the libodfgen package.
Group: Documentation

%description doc
doc components for the libodfgen package.


%package lib
Summary: lib components for the libodfgen package.
Group: Libraries
Requires: libodfgen-license = %{version}-%{release}

%description lib
lib components for the libodfgen package.


%package license
Summary: license components for the libodfgen package.
Group: Default

%description license
license components for the libodfgen package.


%prep
%setup -q -n libodfgen-0.1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553126704
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static --disable-werror
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1553126704
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libodfgen
cp COPYING.LGPL %{buildroot}/usr/share/package-licenses/libodfgen/COPYING.LGPL
cp COPYING.MPL %{buildroot}/usr/share/package-licenses/libodfgen/COPYING.MPL
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libodfgen-0.1/libodfgen/OdfDocumentHandler.hxx
/usr/include/libodfgen-0.1/libodfgen/OdgGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/OdpGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/OdsGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/OdtGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/libodfgen-api.hxx
/usr/include/libodfgen-0.1/libodfgen/libodfgen.hxx
/usr/lib64/libodfgen-0.1.so
/usr/lib64/pkgconfig/libodfgen-0.1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libodfgen/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libodfgen-0.1.so.1
/usr/lib64/libodfgen-0.1.so.1.0.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libodfgen/COPYING.LGPL
/usr/share/package-licenses/libodfgen/COPYING.MPL
