#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libodfgen
Version  : 0.1.8
Release  : 5
URL      : https://dev-www.libreoffice.org/src/libodfgen-0.1.8.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libodfgen-0.1.8.tar.xz
Summary  : Library to generate ODF documents from librevenge's api calls
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: libodfgen-lib = %{version}-%{release}
Requires: libodfgen-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(libxml-2.0)

%description
DESCRIPTION:
libodfgen is a library for generating documents in (surprise!) Open
Document Format (ODF). It provides generator implementations for all
document interfaces supported by librevenge:
* text documents
* vector drawings
* presentations
* spreadsheets
As these APIs are used by multiple libraries, libodfgen can be used to
generate ODF from many sources.

%package dev
Summary: dev components for the libodfgen package.
Group: Development
Requires: libodfgen-lib = %{version}-%{release}
Provides: libodfgen-devel = %{version}-%{release}
Requires: libodfgen = %{version}-%{release}

%description dev
dev components for the libodfgen package.


%package doc
Summary: doc components for the libodfgen package.
Group: Documentation

%description doc
doc components for the libodfgen package.


%package lib
Summary: lib components for the libodfgen package.
Group: Libraries
Requires: libodfgen-license = %{version}-%{release}

%description lib
lib components for the libodfgen package.


%package license
Summary: license components for the libodfgen package.
Group: Default

%description license
license components for the libodfgen package.


%prep
%setup -q -n libodfgen-0.1.8
cd %{_builddir}/libodfgen-0.1.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650911331
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --disable-werror
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1650911331
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libodfgen
cp %{_builddir}/libodfgen-0.1.8/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libodfgen/3704f4680301a60004b20f94e0b5b8c7ff1484a9
cp %{_builddir}/libodfgen-0.1.8/COPYING.MPL %{buildroot}/usr/share/package-licenses/libodfgen/9744cedce099f727b327cd9913a1fdc58a7f5599
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libodfgen-0.1/libodfgen/OdfDocumentHandler.hxx
/usr/include/libodfgen-0.1/libodfgen/OdgGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/OdpGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/OdsGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/OdtGenerator.hxx
/usr/include/libodfgen-0.1/libodfgen/libodfgen-api.hxx
/usr/include/libodfgen-0.1/libodfgen/libodfgen.hxx
/usr/lib64/libodfgen-0.1.so
/usr/lib64/pkgconfig/libodfgen-0.1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libodfgen/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libodfgen-0.1.so.1
/usr/lib64/libodfgen-0.1.so.1.0.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libodfgen/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/libodfgen/9744cedce099f727b327cd9913a1fdc58a7f5599
